// Generated by tools/gen-combat-anatomy.mjs. Do not hand-edit.
// Explicit imports let Vite emit one immutable calibration chunk per visual family.

type CalibrationGroupModule = { COMBAT_ANATOMY_CALIBRATIONS: Readonly<Record<string, unknown>> };

export const COMBAT_ANATOMY_GROUP_LOADERS: Readonly<Record<string, () => Promise<CalibrationGroupModule>>> = Object.freeze({
  "abrams": () => import('./combatAnatomyGroups/abrams.generated.ts'),
  "afv": () => import('./combatAnatomyGroups/afv.generated.ts'),
  "casemate": () => import('./combatAnatomyGroups/casemate.generated.ts'),
  "challenger": () => import('./combatAnatomyGroups/challenger.generated.ts'),
  "core": () => import('./combatAnatomyGroups/core.generated.ts'),
  "franceCore": () => import('./combatAnatomyGroups/franceCore.generated.ts'),
  "germany": () => import('./combatAnatomyGroups/germany.generated.ts'),
  "italy": () => import('./combatAnatomyGroups/italy.generated.ts'),
  "japan": () => import('./combatAnatomyGroups/japan.generated.ts'),
  "korea": () => import('./combatAnatomyGroups/korea.generated.ts'),
  "leopard": () => import('./combatAnatomyGroups/leopard.generated.ts'),
  "merkava": () => import('./combatAnatomyGroups/merkava.generated.ts'),
  "misc": () => import('./combatAnatomyGroups/misc.generated.ts'),
  "modern2": () => import('./combatAnatomyGroups/modern2.generated.ts'),
  "modern3Core": () => import('./combatAnatomyGroups/modern3Core.generated.ts'),
  "patton": () => import('./combatAnatomyGroups/patton.generated.ts'),
  "poland": () => import('./combatAnatomyGroups/poland.generated.ts'),
  "russia": () => import('./combatAnatomyGroups/russia.generated.ts'),
  "sheridan": () => import('./combatAnatomyGroups/sheridan.generated.ts'),
  "sovietHeavy": () => import('./combatAnatomyGroups/sovietHeavy.generated.ts'),
  "sweden": () => import('./combatAnatomyGroups/sweden.generated.ts'),
  "t72": () => import('./combatAnatomyGroups/t72.generated.ts'),
  "t80": () => import('./combatAnatomyGroups/t80.generated.ts'),
  "t90": () => import('./combatAnatomyGroups/t90.generated.ts'),
  "uk": () => import('./combatAnatomyGroups/uk.generated.ts'),
  "ukraine": () => import('./combatAnatomyGroups/ukraine.generated.ts'),
  "ww2": () => import('./combatAnatomyGroups/ww2.generated.ts'),
});
