// Generated by tools/gen-vehicle-marking-seats.mjs.
// Dynamic imports stay explicit so Vite emits one immutable receipt chunk per visual family.

type MarkingSeatGroupModule = { VEHICLE_MARKING_SEATS: Readonly<Record<string, unknown>> };

export const VEHICLE_MARKING_SEAT_GROUP_LOADERS: Readonly<Record<string, () => Promise<MarkingSeatGroupModule>>> = Object.freeze({
  "abrams": () => import('./vehicleMarkingSeatGroups/abrams.generated.ts'),
  "afv": () => import('./vehicleMarkingSeatGroups/afv.generated.ts'),
  "casemate": () => import('./vehicleMarkingSeatGroups/casemate.generated.ts'),
  "challenger": () => import('./vehicleMarkingSeatGroups/challenger.generated.ts'),
  "core": () => import('./vehicleMarkingSeatGroups/core.generated.ts'),
  "franceCore": () => import('./vehicleMarkingSeatGroups/franceCore.generated.ts'),
  "germany": () => import('./vehicleMarkingSeatGroups/germany.generated.ts'),
  "italy": () => import('./vehicleMarkingSeatGroups/italy.generated.ts'),
  "japan": () => import('./vehicleMarkingSeatGroups/japan.generated.ts'),
  "korea": () => import('./vehicleMarkingSeatGroups/korea.generated.ts'),
  "leopard": () => import('./vehicleMarkingSeatGroups/leopard.generated.ts'),
  "merkava": () => import('./vehicleMarkingSeatGroups/merkava.generated.ts'),
  "misc": () => import('./vehicleMarkingSeatGroups/misc.generated.ts'),
  "modern2": () => import('./vehicleMarkingSeatGroups/modern2.generated.ts'),
  "modern3Core": () => import('./vehicleMarkingSeatGroups/modern3Core.generated.ts'),
  "patton": () => import('./vehicleMarkingSeatGroups/patton.generated.ts'),
  "poland": () => import('./vehicleMarkingSeatGroups/poland.generated.ts'),
  "russia": () => import('./vehicleMarkingSeatGroups/russia.generated.ts'),
  "sheridan": () => import('./vehicleMarkingSeatGroups/sheridan.generated.ts'),
  "sovietHeavy": () => import('./vehicleMarkingSeatGroups/sovietHeavy.generated.ts'),
  "sweden": () => import('./vehicleMarkingSeatGroups/sweden.generated.ts'),
  "t72": () => import('./vehicleMarkingSeatGroups/t72.generated.ts'),
  "t80": () => import('./vehicleMarkingSeatGroups/t80.generated.ts'),
  "t90": () => import('./vehicleMarkingSeatGroups/t90.generated.ts'),
  "uk": () => import('./vehicleMarkingSeatGroups/uk.generated.ts'),
  "ukraine": () => import('./vehicleMarkingSeatGroups/ukraine.generated.ts'),
  "ww2": () => import('./vehicleMarkingSeatGroups/ww2.generated.ts'),
});
