// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Michael Woo.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, unknown>> = Object.freeze({
  "leo1a5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          1.2580163,
          0.4883283,
          -0.5203867
        ],
        "quaternion": [
          -0.2055219,
          0.6999873,
          0.1926779,
          0.6562421
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0141106
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.28,
        "pos": [
          -1.2580162,
          0.4883283,
          -0.5203867
        ],
        "quaternion": [
          -0.2055219,
          -0.6999874,
          -0.1926779,
          0.656242
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0141105
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.1718013,
          0.3741,
          0.3375282
        ],
        "quaternion": [
          0,
          -0.5529319,
          0,
          0.8332264
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo1a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0098551
      }
    ]
  },
  "leopard2_proto": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.26,
        "pos": [
          0.62,
          1.22,
          -3.786
        ],
        "quaternion": [
          0,
          1,
          0,
          0
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          1.2285268,
          0.2599383,
          -0.3252579
        ],
        "quaternion": [
          0,
          0.722145,
          0,
          0.6917417
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.26,
        "pos": [
          -1.2285268,
          0.2599383,
          -0.3252579
        ],
        "quaternion": [
          0,
          -0.722145,
          0,
          0.6917417
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a4": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.782075,
          1.1912438,
          -0.7159999
        ],
        "quaternion": [
          -0.0055238,
          -0.7070852,
          -0.0055238,
          0.7070852
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0150881
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.25,
        "pos": [
          -1.782075,
          1.1912438,
          0.5416
        ],
        "quaternion": [
          -0.0055238,
          -0.7070852,
          -0.0055238,
          0.7070852
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4",
        "visibilitySamples": 9,
        "visibilityClearSamples": 8,
        "visibilityRatio": 0.8888889,
        "maximumSurfaceErrorM": 0.027834
      }
    ]
  },
  "leo2a4m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.9335034,
          1.041308,
          -0.8
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          -1.9335034,
          1.041308,
          0.0084999
        ],
        "quaternion": [
          -0.0063639,
          -0.7070781,
          -0.0063639,
          0.7070781
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "leo2a4m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.521,
          0.1695,
          -0.8982
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0014497
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.3159999,
          0.1695,
          -1.5703
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a6": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.4312645,
          0.4107593,
          0.068761
        ],
        "quaternion": [
          -0.0417465,
          -0.7037873,
          -0.0419927,
          0.7079388
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.386,
          0.16036,
          -0.1949958
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a6m": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.2050105,
          0.457671,
          -1.4455143
        ],
        "quaternion": [
          -0.2487083,
          -0.6619246,
          -0.2487083,
          0.6619246
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3729528,
          0.36948,
          -0.8051313
        ],
        "quaternion": [
          0,
          -0.7677987,
          0,
          0.6406912
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6m",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2_revolution": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          1.6088411,
          0.4218878,
          0.525
        ],
        "quaternion": [
          -0.1126766,
          0.6980716,
          0.1126766,
          0.6980716
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.4808134,
          0.2889502,
          -1.5503293
        ],
        "quaternion": [
          -0.0308933,
          0.7369948,
          0.0282779,
          0.6745996
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2_revolution",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0001089
      }
    ]
  },
  "leo2a7v": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.4777862,
          0.4713495,
          -1.2825173
        ],
        "quaternion": [
          -0.1290017,
          -0.696278,
          -0.1286295,
          0.6942693
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a7v",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.4801175,
          0.4713538,
          -0.7270285
        ],
        "quaternion": [
          -0.1293894,
          -0.6968754,
          -0.1287757,
          0.6935704
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a7v",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "kf51": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3452658,
          0.5636752,
          -1.316
        ],
        "quaternion": [
          -0.0863967,
          -0.7018088,
          -0.0863967,
          0.7018088
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3692143,
          0.5641478,
          -0.62575
        ],
        "quaternion": [
          -0.1151318,
          -0.6976709,
          -0.1151318,
          0.6976709
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "kf51b": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4549127,
          0.4168,
          -1.0457587
        ],
        "quaternion": [
          0,
          -0.7449088,
          0,
          0.6671663
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0139033
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.4815036,
          0.4168,
          -0.5056587
        ],
        "quaternion": [
          0,
          -0.7449088,
          0,
          0.6671663
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "kf51b",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "leo2a6_ua": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          0.9021321,
          0.7925773,
          -1.2705714
        ],
        "quaternion": [
          -0.1132659,
          0.6979762,
          0.1132659,
          0.6979762
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6_ua",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0804266
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -0.426,
          1.1136,
          -0.6291143
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "leo2a6_ua",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.3119488
      }
    ]
  }
});
