// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Michael Woo.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, unknown>> = Object.freeze({
  "type59": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.6051776,
          0.2735828,
          -0.2266496
        ],
        "quaternion": [
          -0.0941064,
          0.7008167,
          0.0941064,
          0.7008167
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0132292
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.23,
        "pos": [
          1.3164141,
          0.439827,
          -0.9645273
        ],
        "quaternion": [
          -0.2570755,
          0.8392037,
          0.1403618,
          0.4582007
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type59",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0153825
      }
    ]
  },
  "ztz85_iii": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.957133,
          0.27,
          0.6821886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          1.0668237,
          0.27,
          0.4021886
        ],
        "quaternion": [
          0,
          0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.21,
        "pos": [
          -1.0080608,
          0.27,
          0.5521886
        ],
        "quaternion": [
          0,
          -0.5635773,
          0,
          0.8260633
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      }
    ]
  },
  "type99a": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.302853,
          0.688,
          -0.424775
        ],
        "quaternion": [
          0,
          -0.705632,
          0,
          0.7085785
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type99a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.3481984,
          0.6881721,
          0.023985
        ],
        "quaternion": [
          -0.0101551,
          -0.7079153,
          -0.0101298,
          0.7061517
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "type99a",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "ztz99a2": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          -1.0817587,
          0.5245537,
          0.4219211
        ],
        "quaternion": [
          -0.2612201,
          -0.5212211,
          -0.3640229,
          0.726347
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0647701
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          1.5727646,
          0.3,
          -0.8114696
        ],
        "quaternion": [
          0,
          0.7889665,
          0,
          0.6144362
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0289277
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -1.5727646,
          0.3,
          -0.8114696
        ],
        "quaternion": [
          0,
          -0.7889665,
          0,
          0.6144362
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.0289277
      }
    ]
  },
  "mbt70": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.28,
        "pos": [
          1.7445414,
          1.20029,
          1.82
        ],
        "quaternion": [
          -0.0170924,
          0.7069002,
          0.0170924,
          0.7069002
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": null
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          1.6490909,
          0.4414671,
          -1.7205311
        ],
        "quaternion": [
          -0.091251,
          0.7320722,
          0.0835018,
          0.6699037
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1273932
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.31,
        "pos": [
          -1.6490909,
          0.4414671,
          -1.7205311
        ],
        "quaternion": [
          -0.091251,
          -0.7320722,
          -0.0835018,
          0.6699037
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.1273932
      }
    ]
  },
  "t14": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          1.866,
          1.22,
          3.05
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.051
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          -1.866,
          1.22,
          3.05
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 7,
        "visibilityRatio": 0.7777778,
        "maximumSurfaceErrorM": 0.051
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.24,
        "pos": [
          1.026,
          0.41274,
          -0.7383201
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "t14",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  }
});
