// Generated by tools/gen-vehicle-marking-seats.mjs.
// First-party procedural vehicle artwork and engineering: Michael Woo.

export const VEHICLE_MARKING_SEAT_SCHEMA_VERSION = 1;

export const VEHICLE_MARKING_SEATS: Readonly<Record<string, unknown>> = Object.freeze({
  "chieftain5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.361,
          0.2524608,
          -0.4739999
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0041422
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.3456026,
          0.3164201,
          -0.0396184
        ],
        "quaternion": [
          -0.0276881,
          -0.7135183,
          -0.0271466,
          0.6995628
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0000028
      }
    ]
  },
  "chieftain_mk10": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          1.8215,
          1.17,
          0
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.34,
        "pos": [
          -1.8215,
          1.17,
          0
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.361,
          0.2630432,
          -1.0269999
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "chieftain_mk10",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "fv510": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.24,
        "pos": [
          1.503,
          1.2409524,
          -0.5793
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.812823,
          0.2405097,
          -0.0986994
        ],
        "quaternion": [
          -0.0272535,
          0.6251992,
          0.0339688,
          0.7792492
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0013986
      }
    ]
  },
  "fv510_milan": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.22,
        "pos": [
          -1.503,
          1.21856,
          -0.6406
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "fv510_milan",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.22,
        "pos": [
          0.812823,
          0.2405097,
          -0.0986994
        ],
        "quaternion": [
          -0.0272535,
          0.6251992,
          0.0339688,
          0.7792492
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0645744
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          0.902919,
          0.3,
          -0.4807183
        ],
        "quaternion": [
          0,
          0.7482353,
          0,
          0.6634334
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0324753
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.2,
        "pos": [
          -0.902919,
          0.3,
          -0.4807183
        ],
        "quaternion": [
          0,
          -0.7482353,
          0,
          0.6634334
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 6,
        "visibilityRatio": 0.6666667,
        "maximumSurfaceErrorM": 0.0324753
      }
    ]
  },
  "vickers_mk1": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          1.5669996,
          1.2806091,
          -0.7
        ],
        "quaternion": [
          -0.0359369,
          0.706193,
          0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0004484
      },
      {
        "kind": "designation",
        "parent": "hull",
        "size": 0.3,
        "pos": [
          -1.5669996,
          1.2806091,
          -0.7
        ],
        "quaternion": [
          -0.0359369,
          -0.706193,
          -0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "authored-surface-seat",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0004484
      },
      {
        "kind": "insignia",
        "parent": "hull",
        "size": 0.23,
        "pos": [
          1.5695629,
          1.2554891,
          0.3945
        ],
        "quaternion": [
          -0.0359369,
          0.706193,
          0.0359369,
          0.706193
        ],
        "surfaceMesh": "hull",
        "anchorProfile": "vickers_mk1",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "centurion3": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.471,
          0.3169,
          -0.326
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          -1.5185,
          0.3169,
          0.0425
        ],
        "quaternion": [
          0,
          -0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion3",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0
      }
    ]
  },
  "centurion5": {
    "schemaVersion": 1,
    "seats": [
      {
        "kind": "insignia",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.471,
          0.33135,
          -0.6192001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0022161
      },
      {
        "kind": "designation",
        "parent": "turret",
        "size": 0.25,
        "pos": [
          1.1909999,
          0.41805,
          -1.2176001
        ],
        "quaternion": [
          0,
          0.7071068,
          0,
          0.7071068
        ],
        "surfaceMesh": "turret",
        "anchorProfile": "centurion5",
        "visibilitySamples": 9,
        "visibilityClearSamples": 9,
        "visibilityRatio": 1,
        "maximumSurfaceErrorM": 0.0048049
      }
    ]
  }
});
